// This runner is auto-generated by Brittle

runTests()

async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./markdownToHtml.test.js')
  await import('./rehypeConvertRelativePaths.test.js')

  test.resume()
}
